### ISSUE TITLE
Multiple Authorizations

### ISSUE THREAD

**Issue by tilgovi** [hypothesis/vision#29]
Simultaneous authorizations so you can pull annotations from multiple services.

---

There's a bit to be done to allow real use of multiple, simultaneous authorizations:
- [x] [openannotation/annotator-store](/openannotation/annotator-store) supports only a single authorization at once, via the token header
- [x] [hypothesis/h](/hypothesis/h) needs to pass these authorizations to the store in some sane way
- [ ] [hypothesis/h](/hypothesis/h) needs to allow for multiple authorizations in the front-end
