### ISSUE TITLE
Annotate PDFs

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/vision#49]
Improvements to the ability to annotate PDFs.
- [ ] When I activate the extension on a PDF, I see the sidebar.
- [ ] When selecting text, I see the adder
- [ ] When I save an annotation, the anchor persists. Highlights (if on), show the selection.
- [ ] When I return to the PDF, annotations previously made are re-anchored
